version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: unity-streamlit-app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount the database file if you want to persist data
      - ./db_unity.db:/app/db_unity.db
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
      # Mount temp directory for temporary files
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - unity-network

networks:
  unity-network:
    driver: bridge
