[build]
builder = "dockerfile"

[deploy]
startCommand = "streamlit run FeeModification_app.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
